# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Physical Computing Crash Course
description: > # this means to ignore newlines until "baseurl:"
  Physical computing crash course @ SAE Institute Milan 2016
repository: https://github.com/Limulo/pccc-sae2016
baseurl: #/jekyll-theme-hackcss  # the subpath of your site, e.g. /blog
url: https://limulo.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: limulo.net
email: info@limulo.net

navigation:
  - text: Home
    url: /
  - text: Docs
    url: /docs
  - text: Lezioni
    url: /lezioni

social:
  - service: github
    username: v1a1l1e1
    link: https://github.com/v1a1l1e1
  - service: github
    username: ariutti
    link: https://github.com/ariutti
  - service: twitter
    username: limulo_lab
    link: https://twitter.com/limulo_lab

# Plugins
gems:
  - jekyll-seo-tag
